In [1]:
import torch

In [2]:
# Bias == default when all featues take on value 0, basically offset/
# Default prediction

In [ ]:
# Vectors leads to order of magnitude level improvement in efficiency

## Generating Synthetic Data

In [6]:
def generate_data(w: torch.Tensor, b: torch.Tensor, num_examples: int):
    normal_data = torch.normal(0,1, (num_examples, len(w))) # Generates data of a certain shape, either with a different mean and stddev for each element or a shared one for all elems
    return normal_data

In [9]:
generate_data(torch.rand(5,3), torch.rand(1,3), 15) # Generate a bunch of Gaussian examples with mean 0 and stddev 1
# This could be extremely useful as we could specify a different mean and stddev for each feature

tensor([[-0.8263, -0.3378, -0.7590, -1.3058, -0.0880],
        [ 0.8383, -1.7387, -0.6003,  0.3287,  0.9068],
        [ 1.5445,  0.6526,  0.2522, -0.4596,  0.7441],
        [ 0.6042,  0.8429,  1.4547,  0.6519,  1.7894],
        [ 0.2583, -1.5769,  0.5673, -0.8607, -0.3156],
        [-1.2678,  0.0126, -0.3155,  0.9588, -1.6057],
        [ 0.2643,  0.9876,  0.3120, -0.3836,  1.3716],
        [-0.5624, -0.1780, -0.3913,  1.0896,  0.0967],
        [ 1.6429,  1.4594,  0.5817,  0.0041, -0.1786],
        [ 0.0968, -0.5051, -2.5518, -1.1594,  2.5856],
        [ 0.2620, -0.2029,  2.0110,  1.2230, -2.0159],
        [ 0.3467, -1.5809, -0.0676,  0.7500,  0.8691],
        [ 1.3077,  0.4531,  0.7718,  0.5086,  0.6707],
        [-0.3690,  0.0495,  0.5064, -0.4081, -0.9435],
        [ 0.0292, -0.2160, -0.1685, -1.4968,  0.2747]])

In [33]:
# Different mean and stddev for each feature:
def generate_data_with_custom_dist(mean: torch.Tensor, stddev: torch.Tensor, w: torch.Tensor, b: torch.Tensor, num_examples: int):
    normal_data = [torch.normal(mean,stddev) for i in range(num_examples)] # Generates data of a certain shape, either with a different mean and stddev for each element or a shared one for all elems
    return normal_data

In [34]:
# Generate different features with different means and standard deviations
generate_data_with_custom_dist(torch.Tensor([1,2,3,4,5]), torch.Tensor([1,2,3,4,5]), torch.rand(5,3), torch.rand(1,3), 15)

[tensor([ 2.0262,  5.6668, -0.0356,  5.6359,  2.0021]),
 tensor([ 1.3844,  1.6745, -0.0680,  5.7642, 12.3371]),
 tensor([ 0.8632, -0.1684,  2.3418,  2.9237,  9.4773]),
 tensor([ 0.3060,  0.8906,  1.3358,  0.6612, -6.3763]),
 tensor([0.7846, 3.5069, 2.3805, 7.4205, 5.5446]),
 tensor([ 1.8134,  1.5516,  5.5529,  1.3864, -1.7785]),
 tensor([0.5565, 0.2367, 2.7897, 6.8607, 8.0864]),
 tensor([2.8080, 5.6415, 5.4175, 2.0603, 2.9201]),
 tensor([0.9949, 0.3634, 0.3902, 1.2336, 6.2772]),
 tensor([ 2.0763,  3.6064,  4.3312,  4.7290, 17.3246]),
 tensor([1.4953, 0.1996, 1.7931, 6.3762, 6.0653]),
 tensor([3.1342, 3.6653, 7.9141, 5.7994, 2.7496]),
 tensor([ 0.1325,  2.0292, -1.5745,  3.4429,  5.6390]),
 tensor([0.8177, 2.2541, 7.6830, 9.4916, 3.5884]),
 tensor([2.7237, 2.1966, 6.7975, 2.3307, 3.7033])]

In [103]:
# generating a dataset with Gaussian noise
def generate_dataset(mean: int = 1, 
                     stddev: int = 2, w: 
                     torch.Tensor = torch.rand((5,1)),
                     b: torch.Tensor = torch.rand(1,1), 
                     num_examples: int = 50):
    print(w.shape)
    X = torch.normal(mean, stddev, (num_examples, len(w))) # Generates data of a certain shape, either with a different mean and stddev for each element or a shared one for all elems
    y = torch.mm(X,w)
    y = y + b
    # Adding gaussian noise
    y += torch.normal(0, 0.1, (num_examples,len(w[0])))
    return X, y # Returning feature set, labels

In [104]:
features, labels = generate_dataset(5,7, torch.Tensor([[.1], [.1], [.7], [.05], [.05]]), torch.Tensor([2]), 7)# Labels generating deterministically + some noise with random weights
# for a linearly regressive algorithm with some noise - linear relationship
labels

torch.Size([5, 1])


tensor([[-0.7741],
        [ 6.2064],
        [ 9.5621],
        [ 3.3655],
        [14.0831],
        [ 6.0961],
        [ 9.0736]])

In [105]:
# featues
features # some randomized linear weighting of these + Gaussian noise yields results. To be more definitive, select weights beforehand

tensor([[14.7194, -2.4425, -6.5926, 10.2956, -1.9313],
        [ 4.6789, -2.9116,  5.3034, -1.5714, 10.0874],
        [ 6.8084, 10.4848,  8.4068, -7.6185,  8.0880],
        [ 2.3162, -0.7306,  0.7154, 14.5020, -1.0340],
        [ 9.8748, -1.2867, 15.2288, 10.5760, -1.7192],
        [14.4920,  1.8988,  3.8513, -2.4731, -3.7723],
        [-1.0157,  2.0223,  9.4840,  1.5953,  8.5487]])

The data generated above is Gaussian data generated with a linear relationship

In [112]:
features = features[torch.randperm(features.shape[0])] # Using random permutation we shuffle the numbers up to a certain value, hence shuffling the rows / our training examples

In [114]:
features

tensor([[ 4.6789, -2.9116,  5.3034, -1.5714, 10.0874],
        [ 2.3162, -0.7306,  0.7154, 14.5020, -1.0340],
        [-1.0157,  2.0223,  9.4840,  1.5953,  8.5487],
        [14.4920,  1.8988,  3.8513, -2.4731, -3.7723],
        [14.7194, -2.4425, -6.5926, 10.2956, -1.9313],
        [ 6.8084, 10.4848,  8.4068, -7.6185,  8.0880],
        [ 9.8748, -1.2867, 15.2288, 10.5760, -1.7192]])