In [3]:
import torch

## HelloWorld with Torch Tensors

In [4]:
# arange automatically creates a tensor of size k with increasing values
tensor = torch.arange(12)

In [5]:
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
tensor.shape

torch.Size([12])

In [7]:
# Main type tensor, subtype int tensor
type(tensor)

torch.Tensor

In [8]:
# Inspecting total number of elements - string and repr identical proof of concept
print(tensor.__repr__(), tensor.numel(), sep = " number of elements: ")

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) number of elements: 12


In [9]:
tensor = tensor.reshape(3,4) # each array represents matrix row, represents the 0th axis

In [10]:
torch.randn(3,4) # Can build randomized tensors with n rows and m columns

tensor([[ 0.3366, -0.2770,  2.2712,  0.7931],
        [ 1.4738, -1.5589,  1.0135, -0.3396],
        [ 0.3739,  1.9798,  0.7305,  0.5977]])

In [11]:
# Many numpy command duplicated with tensor type - wrapper on top of numpy array?
ones = torch.ones(3,4) # automatic initialization given dimensions
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
ones * tensor, tensor**ones # Operation is eflementwise

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [13]:
torch.exp(tensor)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [14]:
torch.cat((ones, tensor), dim = 0) # concatenate along columns

tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
torch.cat((ones, tensor), dim = 1)

tensor([[ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.],
        [ 1.,  1.,  1.,  1.,  4.,  5.,  6.,  7.],
        [ 1.,  1.,  1.,  1.,  8.,  9., 10., 11.]])

In [16]:
ones.sum() # Obtain sum of all values (12 1's)

tensor(12.)

In [56]:
ones <= tensor # An elementwise comparison of 2 tensors

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [18]:
# Broadcasting example
t1 = torch.arange(6).reshape(3,2)
t1

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [19]:
t2 = torch.arange(3).reshape(3,1)
t2

tensor([[0],
        [1],
        [2]])

In [20]:
t1+t2 # Matrix 2 expands along the column dimension to fit

tensor([[0, 1],
        [3, 4],
        [6, 7]])

## Expansions
The first array in a broadcast can only duplicate itself along the row dimension, the second array can only duplicate itself along the column dimension (why?)

Answer: arrays must either match in dimensions or have a dimension of one / have that dimension not exist. This is because it is trivial to duplicate an array along a dimension it does not have / make copies of an array as a broadcast strategy. However, it is very difficult to decide how to duplicate and what to duplicate if dimensions are equal and there are multiple instances of an array / matrix (ex: dimension 2 and 3 don't match up - which one of the 2 arrays do we duplicate twice?)

## Indexing

In [21]:
t1[1:3] # Selection of rows, [beginning, end]

tensor([[2, 3],
        [4, 5]])

In [22]:
t1[-1] # Selection of final row

tensor([4, 5])

## Memory Locations

In [23]:
id(t1) # Location of tensor 1 in memory pre-operation

140723677080576

In [24]:
t1 += t2

In [25]:
id(t1) # Mutative data structure

140723677080576

In [28]:
# Converting to and from numpy
t1.numpy()

array([[0, 1],
       [3, 4],
       [6, 7]])

In [30]:
torch.from_numpy(t1.numpy())

tensor([[0, 1],
        [3, 4],
        [6, 7]])

In [48]:
ten = torch.cat((torch.from_numpy(torch.rand((5,3)).numpy()),(torch.rand(5,3))))

In [54]:
torch.Tensor([int(val) for val in ten[0]])

tensor([0., 0., 0.])

## 3 Dimensional Broadcast Test

In [102]:
t = torch.rand((5,2,3))

In [109]:
t + torch.rand((5,1,1)) # Note - any dimension == 1 can be broadcast, otherwise must be identical for operation

tensor([[[0.7810, 1.2762, 1.5454],
         [1.5379, 0.7308, 1.4118]],

        [[1.1206, 1.1705, 0.9501],
         [1.3774, 1.5898, 0.8482]],

        [[1.5665, 1.6866, 1.2830],
         [1.9460, 1.9594, 1.6837]],

        [[1.0390, 0.8497, 1.7292],
         [0.8335, 1.0022, 1.3161]],

        [[0.3505, 0.7790, 0.0634],
         [0.9884, 0.6160, 0.1260]]])

## Pandas to Tensor

In [122]:
import os
import pandas as pd


In [128]:
df = pd.DataFrame({"d": [1,2,3,4]})
df = df.to_numpy() # Series autoconversion works, dataframe autoconversion does not 
df

array([[1],
       [2],
       [3],
       [4]])

In [129]:
torch.tensor(df)

tensor([[1],
        [2],
        [3],
        [4]])

In [155]:
t = torch.ones((3,4,5))

In [135]:
t.T # Autotranspose numpy style

tensor([[[ 0.1707, -1.5705,  0.7338],
         [-1.2607, -0.0720, -0.8981],
         [-0.8535,  0.4821,  1.3532],
         [ 0.9165,  0.0274, -0.6017]],

        [[ 0.6685, -0.4203, -0.4571],
         [ 0.8514, -0.6327,  1.9007],
         [-0.0404, -1.0960,  1.7086],
         [-1.4965, -0.8531, -0.8250]],

        [[-0.1843, -1.2232, -0.6483],
         [-0.2184,  0.0986, -0.9593],
         [-1.2680,  0.3288,  0.1973],
         [ 2.3936, -0.5761, -0.9359]],

        [[ 0.6482,  0.6746, -0.7285],
         [-0.3908,  1.8718, -0.3671],
         [-0.1200, -1.0057,  0.6911],
         [-0.7064, -0.1119,  0.4216]],

        [[ 0.7126,  0.7637,  0.4722],
         [-0.2204,  0.4322,  1.0524],
         [ 1.2137, -0.5648,  0.0616],
         [-0.5221,  0.7943,  0.3094]]])

In [148]:
numpy.transpose(t, [1,0,2]) # Transposition because tensor is a numpy wrapper

tensor([[[ 0.1707,  0.6685, -0.1843,  0.6482,  0.7126],
         [-1.5705, -0.4203, -1.2232,  0.6746,  0.7637],
         [ 0.7338, -0.4571, -0.6483, -0.7285,  0.4722]],

        [[-1.2607,  0.8514, -0.2184, -0.3908, -0.2204],
         [-0.0720, -0.6327,  0.0986,  1.8718,  0.4322],
         [-0.8981,  1.9007, -0.9593, -0.3671,  1.0524]],

        [[-0.8535, -0.0404, -1.2680, -0.1200,  1.2137],
         [ 0.4821, -1.0960,  0.3288, -1.0057, -0.5648],
         [ 1.3532,  1.7086,  0.1973,  0.6911,  0.0616]],

        [[ 0.9165, -1.4965,  2.3936, -0.7064, -0.5221],
         [ 0.0274, -0.8531, -0.5761, -0.1119,  0.7943],
         [-0.6017, -0.8250, -0.9359,  0.4216,  0.3094]]])

In [151]:
len(t), len(t[2][1]) # First dimension returned by len, but can nest

(3, 5)

In [156]:
t2 = torch.ones((3,4,1))


In [158]:
t == t2 # Equality operator wrapped (autobroadcasting, __eq__ overwritten)

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [168]:
import copy

In [172]:
t2.clone() # A deepcopy

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [178]:
type(t2.size()), t2.size() # Torch has size object, addable but non-concatentabale

(torch.Size, torch.Size([3, 4, 1]))

In [180]:
int(torch.tensor(2))+ 2 # Torch tensor with single element can act as scalar

4

In [181]:
t3 = torch.ones((3,4,2))

In [182]:
t3.sum(axis = (1,2)) # Value summed across -> dimension reduced

tensor([8., 8., 8.])